### ISSUE TITLE
Downloading a beta version results in "bad updateIdentity"

### ISSUE THREAD

**Issue by InvoxiPlayGames** [MCMrARM/mc-w10-version-launcher#7]
When attempting to download any version marked as a beta, I get a "bad updateIdentity" error.

![image](https://user-images.githubusercontent.com/22731889/55283356-26d1f700-5359-11e9-85ad-30ef2d8dc764.png)

Every release (non-beta) version of Minecraft works, however this happens with every single beta version of the game.

**Comment by dktapps** [comment]
You have to join the Xbox Insider program for Minecraft in the Insider Hub for this.

**Comment by S3v3Nice** [comment]
> 
> 
> You have to join the Xbox Insider program for Minecraft in the Insider Hub for this.

What if I did it, but installing the beta version still does not work?

**Comment by MCMrARM** [comment]
Make sure you can download it from the Store.
If you still can't, do you have more than one MS account attached?

**Comment by S3v3Nice** [comment]
Yes, I have several MS accounts attached. Do you mean that I have to detach them?

**Comment by MCMrARM** [comment]
The app picks the first account as the one to use currently, I guess I should fix that.

**Comment by NormalOcean6686** [comment]
So is there away to get it to work?

**Comment by AvgZing** [comment]
I can't download from the store either. Is this launcher interfering in any way?

**Comment by AvgZing** [comment]
Bump: I can download from the store but I encounter an error while downloading beta OR stable from the store. My primary account is the one registered to the beta, so that shouldn't be an issue. Yet, I still encounter this issue.

**Comment by KastetPrivet** [comment]
я всё сделал,но почему-то всё равно бета-версии не запускаются

I did everything, but for some reason the beta versions still do not start

**Comment by southvietnamrepublic** [comment]
mine minecraft version manager version is installed but can't launch 
![image](https://user-images.githubusercontent.com/96936657/147870056-d8955f85-1025-4c58-b424-f66bcaeb9993.png)
